### ISSUE TITLE
Webpack 4 help - using in conjunction with mini-css-extract-plugin

### ISSUE THREAD

**Issue by iongion** [shepherdwind/css-hot-loader#36]
Webpack 4 has issues with the extract text plugin
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues

So now, the recommended solution is to use [`mini-css-extract-plugin`](https://github.com/webpack-contrib/mini-css-extract-plugin), but that one does not work with the hot reload.

I have attached a zip with sample use, I do not know where the issues lies, in `css-hot-loader` or `mini-css-extract-plugin`

[react-demo.zip](https://github.com/shepherdwind/css-hot-loader/files/1796299/react-demo.zip)

**Comment by iongion** [comment]
Feel free to close this issue if you notice that the fix really needs to be applied in the `mini-css-extract-plugin` project.

**Comment by shepherdwind** [comment]
This  problem should fixed in `mini-css-extract-plugin`. I tried `mini-css-extract-plugin` with `css-hot-loader`, when css changed, `css-hot-loader` will reload css ,but this css file not changed.

So, I remove the css-hot-loader plugin, then change css file, reload the css file manual. But The css context not change too. So this is not the problem of css-hot-loader. 

I think the issue case by https://github.com/webpack-contrib/mini-css-extract-plugin/issues/23 .
